name: test_dbt_1
version: 1.0.0
config-version: 2
profile: test_dbt_1
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  test_dbt_1:
    +materialized: view
